export const MODULE_ID = "advanced-drawing-tools";
export const MODULE_NAME = "Advanced Drawing Tools";
export const DEFAULT_FLAGS = Object.freeze({
    [`flags.${MODULE_ID}.fillStyle.texture.height`]: null,
    [`flags.${MODULE_ID}.fillStyle.texture.width`]: null,
    [`flags.${MODULE_ID}.fillStyle.transform.pivot.x`]: 0,
    [`flags.${MODULE_ID}.fillStyle.transform.pivot.y`]: 0,
    [`flags.${MODULE_ID}.fillStyle.transform.position.x`]: 0,
    [`flags.${MODULE_ID}.fillStyle.transform.position.y`]: 0,
    [`flags.${MODULE_ID}.fillStyle.transform.rotation`]: 0,
    [`flags.${MODULE_ID}.fillStyle.transform.scale.x`]: 1,
    [`flags.${MODULE_ID}.fillStyle.transform.scale.y`]: 1,
    [`flags.${MODULE_ID}.fillStyle.transform.skew.x`]: 0,
    [`flags.${MODULE_ID}.fillStyle.transform.skew.y`]: 0,
    [`flags.${MODULE_ID}.lineStyle.dash`]: null,
    [`flags.${MODULE_ID}.textStyle.align`]: null,
    [`flags.${MODULE_ID}.textStyle.dropShadow`]: true,
    [`flags.${MODULE_ID}.textStyle.dropShadowAlpha`]: 1,
    [`flags.${MODULE_ID}.textStyle.dropShadowAngle`]: 0,
    [`flags.${MODULE_ID}.textStyle.dropShadowBlur`]: null,
    [`flags.${MODULE_ID}.textStyle.dropShadowColor`]: "#000000",
    [`flags.${MODULE_ID}.textStyle.dropShadowDistance`]: 0,
    [`flags.${MODULE_ID}.textStyle.arc`]: 0,
    [`flags.${MODULE_ID}.textStyle.fill`]: [],
    [`flags.${MODULE_ID}.textStyle.fillGradientStops`]: [],
    [`flags.${MODULE_ID}.textStyle.fillGradientType`]: 0,
    [`flags.${MODULE_ID}.textStyle.fontStyle`]: "normal",
    [`flags.${MODULE_ID}.textStyle.fontVariant`]: "normal",
    [`flags.${MODULE_ID}.textStyle.fontWeight`]: "normal",
    [`flags.${MODULE_ID}.textStyle.leading`]: 0,
    [`flags.${MODULE_ID}.textStyle.letterSpacing`]: 0,
    [`flags.${MODULE_ID}.textStyle.stroke`]: null,
    [`flags.${MODULE_ID}.textStyle.strokeThickness`]: null,
    [`flags.${MODULE_ID}.textStyle.wordWrapWidth`]: "100%"
});
